version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: skypoint-postgres
    environment:
      POSTGRES_USER: skypoint_user
      POSTGRES_PASSWORD: skypoint_password
      POSTGRES_DB: skypoint_social
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skypoint_user -d skypoint_social"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skypoint-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skypoint.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: